[stt.parakeet-tdt-0_6b-v3-int8]
files = [
    "encoder-model.int8.onnx",
    "decoder_joint-model.int8.onnx",
    "nemo128.onnx",
    "vocabulary.txt",
]

[stt.parakeet-tdt-0_6b-v3-fp32]
files = [
    "encoder-model.onnx",
    "decoder_joint-model.onnx",
    "encoder-model.onnx.data",
    "nemo128.onnx",
    "vocabulary.txt",
]

[vad.silero-v5]
files = ["silero.onnx"]